#!/usr/bin/env php
<?php
require(__DIR__.'/vendor/autoload.php');
require(__DIR__.'/src/CauchemarsCommand.php');

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CauchemarsCommand);
$application->run();
